name: Doxygen

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  generate-docs:
    name: Generate Doxygen documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Doxygen & Graphviz
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq doxygen graphviz

      - name: Show Doxygen version
        run: doxygen --version

      - name: Generate documentation
        run: doxygen doxygen/Doxyfile

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: docs-gen/html
          retention-days: 14
